trigger:
- master

jobs:
- job: Build
  timeoutInMinutes: 0
  pool:
    vmImage: 'macos-10.14'
  steps:
  - script: |
      ./ci-build-mac.sh
    displayName: 'ci-build'
    timeoutInMinutes: 0
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: swiftwasm-sdk-mac
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: github-release
      tagSource: manual
      tag: $(Build.BuildNumber).mac
      assets: |
        $(Build.ArtifactStagingDirectory)/*
